server:
  port: 3333

buildType: Debug # Debug | Release

db:
  mysql:
    dsn: root:0228@tcp(127.0.0.1:3306)/bronya?charset=utf8mb4&parseTime=True&loc=Local

  maxIdleConns: 2    # 最大空闲连接数，默认 2
  maxOpenConns: 0    # 最大连接数，默认 0，表示无限制
  connMaxLifetime: 0 # 最长连接时间，默认 0，表示无限制

  redis:
    addr: 127.0.0.1:6379
    expiration: 600 # 单位 s

jwt:
  expiration: 1800 # 单位 s
  signingKey: bronya.com # 签名密钥
