server:
  port: 3333

buildType: Debug # Debug | Release

db:
  mysqlDsn: root:0228@tcp(127.0.0.1:3306)/bronya?charset=utf8mb4&parseTime=True&loc=Local

  paginate:
    curr: 1 # 当前页号，从 1 开始，默认 1
    limit: 10 # 每页记录数，默认 10

redis:
  addr: 127.0.0.1:6379
  expire: 60

jwt:
  expire: 60 # 单位 s
  signingKey: bronya.com # 签名密钥
